### ISSUE TITLE
viewer crashing / pcaps transiantly contain malformed packets

### ISSUE THREAD

**Issue by bf31415** [arkime/arkime#1302]
**Elasticsearch version**:

7.1

**Moloch version**:

2.0 (protocolrefactor branch)

**OS name and version**:

ubuntu 16.04

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

easybutton

**Provide logs, stack traces and steps to reproduce**:

I've got an external analytic real-time querying elastic for specific session types and events.   When it sees a session of interest, it takes the id value (it got from elastic) and then does a query to the viewer to grab the pcap.   The analytic is always looking for the most recent session data and corresponding pcap. 

See the error in viewer log below.   At times, the pcaps seem to be semi corrupted.  see below.  

is it guaranteed that the pcap associated to a session is written to disk and file closed by the time the corresponding session data would appear in elastic?  In the pcap example below, it shows two correct ethernet frames followed by corrupted frames (via pulling pcap via viewer) but if I wait a few more seconds and then re-pull that pcap (via viewer) i no longer see the corrupted packets.  

<img width="1159" alt="Screen Shot 2019-11-10 at 06 44 55" src="https://user-images.githubusercontent.com/8351399/68544985-f9850700-0385-11ea-807f-f88958aa459d.png">

same pcap a few seconds later:
<img width="1157" alt="Screen Shot 2019-11-10 at 06 53 58" src="https://user-images.githubusercontent.com/8351399/68545104-f6d6e180-0386-11ea-8b14-c5147165c1af.png">

viewer log:

Sun, 10 Nov 2019 13:31:19 GMT - GET /sessions.pcap?expression=id=191110-0AGsnwHso4dBwrCWhtErw0g- 401 - bytes 0.335 ms
ERROR - processSessionIdDisk - 191110-0AGsnwHso4dBwrCWhtErw0g- in file /elastic/moloch/raw/moloch-dev-191110-00000031.pcap couldn't read packet at 78753 packet # 0 of 3
Trace: writePcap 191110-0AGsnwHso4dBwrCWhtErw0g- in file /elastic/moloch/raw/moloch-dev-191110-00000031.pcap couldn't read packet at 78753 packet # 0 of 3
    at /data/moloch/viewer/viewer.js:6007:15
    at /data/moloch/viewer/viewer.js:5432:18
    at /data/moloch/viewer/viewer.js:5319:9
    at fs.read (/data/moloch/viewer/pcap.js:201:16)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:467:17)
Sun, 10 Nov 2019 13:31:19 GMT admin GET /sessions.pcap?expression=id=191110-0AGsnwHso4dBwrCWhtErw0g- 200 - bytes 8.926 ms
ERROR - processSessionIdDisk - 191110-0AGsnwHso4dBwrCWhtErw0g- in file /elastic/moloch/raw/moloch-dev-191110-00000031.pcap couldn't read packet at 78885 packet # 1 of 3
Trace: writePcap 191110-0AGsnwHso4dBwrCWhtErw0g- in file /elastic/moloch/raw/moloch-dev-191110-00000031.pcap couldn't read packet at 78885 packet # 1 of 3
    at /data/moloch/viewer/viewer.js:6007:15
    at /data/moloch/viewer/viewer.js:5432:18
    at /data/moloch/viewer/viewer.js:5319:9
    at fs.read (/data/moloch/viewer/pcap.js:201:16)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:467:17)
/data/moloch/node_modules/async/dist/async.js:966
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /data/moloch/node_modules/async/dist/async.js:966:32
    at /data/moloch/viewer/viewer.js:6008:14
    at /data/moloch/viewer/viewer.js:5432:18
    at /data/moloch/viewer/viewer.js:5319:9
    at fs.read (/data/moloch/viewer/pcap.js:201:16)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:467:17)

**Comment by bf31415** [comment]
A bit more insight that may help identify the issue.   Below shows the pcap of interest.  Highlighted in blue is the pcap and size when it's malformed.  and then above that line you see i downloaded the pcap two more times (a few minutes later)-- those two pcaps show a smaller size and the pcap does not contain any malformed frames.

<img width="959" alt="Screen Shot 2019-11-10 at 07 00 28" src="https://user-images.githubusercontent.com/8351399/68545196-ed9a4480-0387-11ea-8080-688f7b5b70d0.png">
