### ISSUE TITLE
Error: Cannot find module './lib/mediaType'

### ISSUE THREAD

**Issue by Wapiti08** [arkime/arkime#1558]
**Elasticsearch version**:
7.8
**Moloch version**:
2.7.1
**OS name and version**:
Debian GNU/Linux 10 (buster) 
**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
deb
**Provide logs, stack traces and steps to reproduce**:
Error: Cannot find module './lib/mediaType'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at loadModule (/data/moloch/node_modules/negotiator/index.js:114:16)
    at Negotiator.mediaTypes (/data/moloch/node_modules/negotiator/index.js:76:29)
    at Accepts.type.Accepts.types (/data/moloch/node_modules/accepts/index.js:105:33)
    at IncomingMessage.req.accepts (/data/moloch/node_modules/express/lib/request.js:134:23)
    at ServerResponse.res.format (/data/moloch/node_modules/express/lib/response.js:664:11)
    at ServerResponse.redirect (/data/moloch/node_modules/express/lib/response.js:925:8)
    at /data/moloch/viewer/viewer.js:1176:9
    at Layer.handle [as handle_request] (/data/moloch/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/moloch/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/data/moloch/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/data/moloch/node_modules/express/lib/router/layer.js:95:5)
    at /data/moloch/node_modules/express/lib/router/index.js:281:22

**Comment by awick** [comment]
Need more information please
* what is the url you downloaded from
* what action are you performing, or is this just on viewer start up?

When I look at line 1176 in viewer.js for 2.7.1 it is blank, so I'm wondering if you modified some files?

I tried https://s3.amazonaws.com/files.molo.ch/builds/ubuntu-18.04/moloch_2.7.1-1_amd64.deb on docker run -it debian:buster  bash and it seems to start

**Comment by Wapiti08** [comment]
It's a problem coming from NPM.

**Comment by awick** [comment]
why are you running NPB if you are using the deb?

**Comment by Wapiti08** [comment]
```
ERROR - Couldn't load some dependancies, maybe need to 'npm update' inside viewer directory Error: No such module: http_parser_llhttp
    at process.binding (internal/bootstrap/loaders.js:81:36)
    at Object.<anonymous> (/data/moloch/viewer/decode.js:26:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/data/moloch/viewer/viewer.js:44:16)

**Comment by awick** [comment]
did you mean to close this issue?  If not please reopen.
What version of node are you using, looks like you are using the wrong one. You should use the one included.

**Comment by Wapiti08** [comment]
> 
> 
> why are you running NPM if you are using the deb?

Cuz as for the error, I found the solution to solve Negotiator problem by:
```
npm install negotiator
```
Then I fixed this problem. But I got another problem as I gave above.

**Comment by awick** [comment]
Are you trying to build yourself or run from the deb? If deb, please provide the url?

**Comment by Wapiti08** [comment]
I tried both:
https://s3.amazonaws.com/files.molo.ch/builds/ubuntu-18.04/moloch_2.7.1-1_amd64.deb
https://s3.amazonaws.com/files.molo.ch/builds/ubuntu-20.04/moloch_2.7.1-1_amd64.deb

**Comment by awick** [comment]
You should use 18 if it is based on 18. Please wipe everything and start over. Make sure you are using /data/moloch/bin/node from the viewer directory. You do NOT need to run npb if you installed from deb.

**Comment by Wapiti08** [comment]
> 
> 
> Are you trying to build yourself or run from the deb? If deb, please provide the url?

Yes. Any My elasticsearch version is 7.8.0. The default version seems to be 7.7.1. So I did not install it.

**Comment by Wapiti08** [comment]
My OS version is Debian GNU/Linux 10 (buster).

**Comment by awick** [comment]
it is fine to use your own ES

**Comment by awick** [comment]
please come to slack, this would be much easier to discuss there

**Comment by Wapiti08** [comment]
Okay. I will try. Thanks for your support. I posted the error on slack. No one can solve or answer.

**Comment by awick** [comment]
I did reply to your slack

**Comment by Wapiti08** [comment]
Hahaha. I just found it. Talk there. Thanks

**Comment by awick** [comment]
Incase anyone else hits the problem. The issue ended up being that the package wasn't installed, just downloaded and extracted. This led to all the paths being wrong and confusion. Use `dpkg -i` not `dpkg -x`
