### ISSUE TITLE
viewer custom report issues with fields nested deeper than 2 levels

### ISSUE THREAD

**Issue by mmguero** [arkime/arkime#1781]
**Describe the bug**

I've been renaming the fields under my custom WISE data source to follow the pattern `tool.logtype.field` instead of `tool_logtype.field` as it's more in-line with common practices in designing hierarchical attribute/value schemas seen elsewhere (e.g., ECS). So, for example, what was `zeek_bacnet.function` would be now `zeek.bacnet.function`

I've found two issues so far in making these changes:

First, the `require:` field had an issue which would make the custom view not show up (except the header). @awick looked at it and said:

> looks like its a bug in viewer.js when dealing with require. [...] the issue is with

```
    const parts = ViewerUtils.splitRemain(info.dbField, '.', 1);
    if (parts.length === 1) {
      output += `      +arrayList(session, '${parts[0]}', '${info.friendlyName}', '${field}')\n`;
    } else {
      output += `      +arrayList(session.${parts[0]}, '${parts[1]}', '${info.friendlyName}', '${field}')\n`;
    }
```

> really it should be whatever is after the last dot should be parts[1], and everything before the last dot should be parts[0]. Right now it does the opposite.

I played around with this and changed the line calling `splitRemain` to this using a regular expression lookahead:

```
const parts = info.dbField.split(/\.(?=[^\.]+$)/);
```

And that seemed to fix the problem.

A second, related issue is when opening an Arkime Session record (not one of my custom data source's records) in the session viewer:

```
TypeError: sessionDetail:296
    294|           moloch-session-field.detail-field(:expr="'cert.curve'", :value='"'+cert.curve+'"', :field="fields['cert.curve']", :pull-left="true")
    295|   
  > 296|   if (session.zeek.bacnet)
    297|     h4.sessionDetailMeta Zeek bacnet.log
    298|     dl
    299|       +arrayList(session.zeek.bacnet, 'bvlc_function', 'BVLC Function', 'zeek.bacnet.bvlc_function')

Cannot read property 'bacnet' of undefined
    at eval (eval at wrap (/opt/arkime/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:3092:19)
    at template (eval at wrap (/opt/arkime/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:5654:7)
    at Object.exports.render (/opt/arkime/node_modules/pug/lib/index.js:421:43)
    at Object.exports.render (/opt/arkime/node_modules/pug/lib/index.js:407:21)
    at /opt/arkime/viewer/apiSessions.js:2543:13
    at /opt/arkime/viewer/viewerUtils.js:413:7
    at /opt/arkime/node_modules/async/dist/async.js:473:16
    at replenish (/opt/arkime/node_modules/async/dist/async.js:1006:25)
    at iterateeCallback (/opt/arkime/node_modules/async/dist/async.js:995:17)
    at /opt/arkime/node_modules/async/dist/async.js:969:16
    at /opt/arkime/viewer/viewerUtils.js:408:9
    at Immediate._onImmediate (/opt/arkime/viewer/db.js:1686:7)
    at processImmediate (internal/timers.js:464:21)
```

So it looks like the code generated from the config.ini line for that view is trying to check `session.zeek.bacnet` but in this case `session.zeek` itself doesn't exist. But I mean, hypothetically it could be 2, 3, 4, etc. levels deep (`session.zeek.tls.client.ja3` or whatever).

@awick said that PUG doesn't support the optional chaining operator (`?.`) or `try`/`catch`, so the best way to approach this may be to put multiple levels of checks in the if (?).

**Elasticsearch version**: v7.10.2

**Arkime/Moloch version**: v3.1.1

**OS name and version**: Debian Linux 11

**How was Arkime/Moloch built/installed:** easybutton in Docker

**Provide logs, stack traces and steps to reproduce**: See description

**Comment by mmguero** [comment]
Here's the issue for PUG on the optional chaining operator pugjs/pug#3292 not being supported
