### ISSUE TITLE
export PCAP fails if there are any "sessions" without packets

### ISSUE THREAD

**Issue by mmguero** [arkime/arkime#1952]
**Describe the bug**

If you attempt to do an **Export PCAP** from the sessions view (using the dropdown to the right of the search bar) for visible sessions when some of the sessions which will be included are not backed by PCAP (in my case they are session documents written via logstash but otherwise matching the same schema as the native arkime session documents), an error is raised and no PCAP is exported. See log at the bottom of this bug report.

I'm running v3.4.2, [here's the line number at `apiSessions.js:1147`](https://github.com/arkime/arkime/blob/v3.4.2/viewer/apiSessions.js#L1147) it's complaining about.

I think a check needs to be placed in here somewhere to not attempt to retrieve `packetPos`/packet location/payload if no packet is present.

**Elasticsearch version**:

OpenSearch v2.1.0

**Arkime/Moloch version**:

Arkime v3.4.2

**OS name and version**:

Debian 11 (x86_64 Linux)

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)

[easybutton build in Docker](https://github.com/mmguero-dev/Malcolm/blob/11ab87ebcde33657fe4928e18ba27381fe658848/Dockerfiles/arkime.Dockerfile#L83)

**Provide logs, stack traces and steps to reproduce**:

Logs:

```
Trace: ES Search Error - query: {
  "index": "arkime_sessions3-220802",
  "body": {
    "query": {
      "ids": {
        "values": [
          "220802-aH83zjkVmIf3-4352CFPsw"
        ]
      }
    },
    "_source": false,
    "fields": [
      "node",
      "network.packets",
      "packetPos",
      "source.ip",
      "source.port",
      "destination.ip",
      "destination.port",
      "ipProtocol",
      "packetLen"
    ],
    "profile": false
  },
  "rest_total_hits_as_int": true
} err: TypeError: Cannot read properties of undefined (reading 'length')
    at /opt/arkime/viewer/apiSessions.js:1147:43
    at fixPacketPos (/opt/arkime/viewer/db.js:408:14)
    at /opt/arkime/viewer/db.js:532:12
    at Object.exports.search (/opt/arkime/viewer/db.js:570:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.exports.search (/opt/arkime/viewer/db.js:572:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERROR - session get error in processSessionId TypeError: Cannot read properties of undefined (reading 'length')
    at /opt/arkime/viewer/apiSessions.js:1147:43
    at fixPacketPos (/opt/arkime/viewer/db.js:408:14)
    at /opt/arkime/viewer/db.js:532:12
    at Object.exports.search (/opt/arkime/viewer/db.js:570:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) undefined
Trace: writePcap Session not found
    at /opt/arkime/viewer/apiSessions.js:910:19
    at /opt/arkime/viewer/apiSessions.js:1122:16
    at /opt/arkime/viewer/db.js:510:23
    at Object.exports.search (/opt/arkime/viewer/db.js:573:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Here is the corresponding document's (id `220802-aH83zjkVmIf3-4352CFPsw` as you can see in the trace) JSON:

```
{
    "@timestamp": "2022-08-02T01:04:32.077Z",
    "@version": "1",
    "agent": {
        "hostname": "filebeat",
        "name": "sgrover"
    },
    "destination": {
        "ip": "172.16.0.20"
    },
    "ecs": {
        "version": "1.6.0"
    },
    "event": {
        "category": [
            "file"
        ],
        "dataset": "files",
        "end": "1659402272077",
        "hash": "aH83zjkVmIf3-4352CFPsw",
        "id": [
            "CRfJmlrczVouNL1Jh",
            "Fr0r9v1OuiuJBqN9j4"
        ],
        "ingested": "2022-08-02T01:04:36.499Z",
        "kind": "event",
        "provider": "zeek",
        "start": "1659402272077"
    },
    "file": {
        "hash": {
            "md5": "8b05ce45d0df59343e206bc9ae78d85d",
            "sha1": "03f4586f778b80d8dc1f2dc2eaad43b2009e1d84"
        },
        "mime_type": [
            "image/png"
        ],
        "size": "54413",
        "source": "HTTP",
        "type": "file"
    },
    "firstPacket": 1659402272077,
    "host": {
        "name": "sgrover"
    },
    "input": {},
    "lastPacket": 1659402272077,
    "length": 0,
    "log": {
        "file": {
            "path": "files.log"
        }
    },
    "network": {
        "application": "http",
        "bytes": 54413,
        "direction": "internal",
        "protocol": [
            "http"
        ],
        "type": "ipv4"
    },
    "node": "sgrover",
    "protocol": [
        "http",
        "http"
    ],
    "related": {
        "hash": [
            "8b05ce45d0df59343e206bc9ae78d85d",
            "03f4586f778b80d8dc1f2dc2eaad43b2009e1d84"
        ],
        "ip": [
            "172.16.0.20",
            "172.16.0.33"
        ]
    },
    "rootId": "CRfJmlrczVouNL1Jh",
    "source": {
        "ip": "172.16.0.33"
    },
    "tags": [
        "internal_source",
        "internal_destination"
    ],
    "timestamp": 1659402272077,
    "totDataBytes": 54413,
    "zeek": {
        "files": {
            "analyzers": [
                "MD5",
                "PE_XOR",
                "SHA1"
            ],
            "conn_uids": [
                "CRfJmlrczVouNL1Jh"
            ],
            "depth": "0",
            "duration": "0.006812",
            "is_orig": "F",
            "local_orig": "T",
            "md5": "8b05ce45d0df59343e206bc9ae78d85d",
            "mime_type": "image/png",
            "missing_bytes": "0",
            "overflow_bytes": "0",
            "rx_hosts": [
                "172.16.0.20"
            ],
            "seen_bytes": "54413",
            "sha1": "03f4586f778b80d8dc1f2dc2eaad43b2009e1d84",
            "timedout": "F",
            "total_bytes": "54413",
            "tx_hosts": [
                "172.16.0.33"
            ]
        },
        "fuid": [
            "Fr0r9v1OuiuJBqN9j4"
        ],
        "ts": "2022-08-02T01:04:32.077Z",
        "uid": "CRfJmlrczVouNL1Jh"
    }
}
```

**Comment by mmguero** [comment]
There is [a check in `fixPacketPos` in `db.js`](https://github.com/arkime/arkime/blob/55175fc5c69743452ba3326f067fd4a17a3360e9/viewer/db.js#L401) that I think is very similar to what would need to be done here.

**Comment by mmguero** [comment]
Although it doesn't seem to be *quite* as simple as putting `if (fields.packetPos) {` around that for loop, as I tried that and `Export PCAP` just seemed to never return.

**Comment by mmguero** [comment]
I think the reason it never returned when I put the `if (fields.packetPos) {` is that it never hits the `readyToProcess` because of the i/ilen/outstanding check. I'm going to try it again

**Comment by mmguero** [comment]
Woohoo, my fix worked, I'll submit a PR for your review.

**Comment by mmguero** [comment]
Oops, lol, didn't mean to close.

**Comment by mmguero** [comment]
Fixed with #1953
