### ISSUE TITLE
Cont3xt with OIDC crashes while redirecting

### ISSUE THREAD

**Issue by mcgillowen** [arkime/arkime#2771]
**Describe the bug**

Cont3xt crashes when using OIDC auth after successful login with the OIDC provider. Cont3xt attempts to redirect to original URL put tries to access an undefined field on the request object.

```
/opt/arkime/common/auth.js:780
          if (req.body.ogurl) {
                       ^

TypeError: Cannot read properties of undefined (reading 'ogurl')
    at /opt/arkime/common/auth.js:780:24
    at complete (/opt/arkime/node_modules/passport/lib/middleware/authenticate.js:271:13)
    at /opt/arkime/node_modules/passport/lib/middleware/authenticate.js:278:15
    at pass (/opt/arkime/node_modules/passport/lib/authenticator.js:428:14)
    at Authenticator.transformAuthInfo (/opt/arkime/node_modules/passport/lib/authenticator.js:450:5)
    at /opt/arkime/node_modules/passport/lib/middleware/authenticate.js:275:22
    at /opt/arkime/node_modules/passport/lib/http/request.js:41:7
    at /opt/arkime/node_modules/passport/lib/sessionmanager.js:51:9
    at /opt/arkime/common/auth.js:1143:7
    at onBody (/opt/arkime/node_modules/@elastic/elasticsearch/lib/Transport.js:320:9)
```

**Elasticsearch version**: 8.8.2

**Arkime/Moloch version**: 5.1.0

**OS name and version**: Ubuntu 20.04

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...) easybutton

**Provide logs, stack traces and steps to reproduce**:

1. Enable OIDC auth 
2. Try to login
3. Cont3xt returns a 500 and crashes with the following log

```
/opt/arkime/common/auth.js:780
          if (req.body.ogurl) {
                       ^

TypeError: Cannot read properties of undefined (reading 'ogurl')
    at /opt/arkime/common/auth.js:780:24
    at complete (/opt/arkime/node_modules/passport/lib/middleware/authenticate.js:271:13)
    at /opt/arkime/node_modules/passport/lib/middleware/authenticate.js:278:15
    at pass (/opt/arkime/node_modules/passport/lib/authenticator.js:428:14)
    at Authenticator.transformAuthInfo (/opt/arkime/node_modules/passport/lib/authenticator.js:450:5)
    at /opt/arkime/node_modules/passport/lib/middleware/authenticate.js:275:22
    at /opt/arkime/node_modules/passport/lib/http/request.js:41:7
    at /opt/arkime/node_modules/passport/lib/sessionmanager.js:51:9
    at /opt/arkime/common/auth.js:1143:7
    at onBody (/opt/arkime/node_modules/@elastic/elasticsearch/lib/Transport.js:320:9)
```

**Comment by awick** [comment]
The line numbers don't seem to match up, has auth.js been modified?
Unfortunately this is a works for me, so any other info you can share? Which OIDC provider are you using? It looks like the req.body is missing.

**Comment by mcgillowen** [comment]
Sorry, just noticed that the log output was from v5.0.1, I tried again this time with v5.1.0 and the line numbers match up now

```
Wed, 01 May 2024 13:04:11 GMT - GET / 302 0 bytes 9.663 ms
/opt/arkime/common/auth.js:783
          if (req.body.ogurl) {
                       ^

TypeError: Cannot read properties of undefined (reading 'ogurl')
    at /opt/arkime/common/auth.js:783:24
    at complete (/opt/arkime/node_modules/passport/lib/middleware/authenticate.js:280:13)
    at /opt/arkime/node_modules/passport/lib/middleware/authenticate.js:287:15
    at pass (/opt/arkime/node_modules/passport/lib/authenticator.js:446:14)
    at Authenticator.transformAuthInfo (/opt/arkime/node_modules/passport/lib/authenticator.js:468:5)
    at /opt/arkime/node_modules/passport/lib/middleware/authenticate.js:284:22
    at /opt/arkime/node_modules/passport/lib/http/request.js:41:7
    at /opt/arkime/node_modules/passport/lib/sessionmanager.js:51:9
    at /opt/arkime/common/auth.js:1146:7
    at onBody (/opt/arkime/node_modules/@elastic/elasticsearch/lib/Transport.js:320:9)

Node.js v18.20.1
```

**Comment by mcgillowen** [comment]
I'm using Keycloak and the `authRedirectURIs` is set to https://context.mcgillowen.local/auth/login/callback

**Comment by awick** [comment]
Ok, I'll try and reproduce, for now you could change it to `if (req.body?.ogurl) {`
