### ISSUE TITLE
Viewer crashes due to undefined values

### ISSUE THREAD

**Issue by cpockrandt** [arkime/arkime#2839]
**Describe the bug**

When browsing through the viewer, it crashed a few times when encountering undefined values. I captured the stack traces below. We use a vanilla setup of Arkime, but capture and view the pcap files from S3 storage.

**Elasticsearch version**:

2.11.1

**Arkime/Moloch version**:

5.0.2

**OS name and version**:

Kubernetes

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)

Built from source using tarball

**Provide logs, stack traces and steps to reproduce**:

```
Fri, 23 Feb 2024 15:08:49 GMT admin GET /api/session/xxx/yyyyyyyyyy/detail 200 - bytes 528.139 ms
/opt/arkime/viewer/pcap.js:1118
        const newBuf = Buffer.alloc(results[results.length - 1].data.length + item.ether.data.length);
                                                                     ^

TypeError: Cannot read properties of undefined (reading 'length')
    at /opt/arkime/viewer/pcap.js:1118:70
    at Array.forEach (<anonymous>)
    at Pcap.reassemble_generic_ether (/opt/arkime/viewer/pcap.js:1108:13)
    at /opt/arkime/viewer/apiSessions.js:586:14
    at ViewerUtils.fixFields (/opt/arkime/viewer/viewerUtils.js:412:14)
    at /opt/arkime/viewer/apiSessions.js:1285:21
    at /opt/arkime/viewer/apiSessions.js:810:7
    at wrapper (/opt/arkime/node_modules/async/dist/async.js:271:20)
    at replenish (/opt/arkime/node_modules/async/dist/async.js:441:29)
    at iterateeCallback (/opt/arkime/node_modules/async/dist/async.js:430:21)
    at /opt/arkime/node_modules/async/dist/async.js:327:20
    at invokeCallback (/opt/arkime/node_modules/async/dist/async.js:182:13)
    at /opt/arkime/node_modules/async/dist/async.js:174:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.19.1
```

```
/opt/arkime/viewer/pcap.js:1109
      const key = item.ether.addr1;
                             ^

TypeError: Cannot read properties of undefined (reading 'addr1')
    at /opt/arkime/viewer/pcap.js:1109:30
    at Array.forEach (<anonymous>)
    at Pcap.reassemble_generic_ether (/opt/arkime/viewer/pcap.js:1108:13)
    at /opt/arkime/viewer/apiSessions.js:586:14
    at ViewerUtils.fixFields (/opt/arkime/viewer/viewerUtils.js:412:14)
    at /opt/arkime/viewer/apiSessions.js:1285:21
    at /opt/arkime/viewer/apiSessions.js:810:7
    at wrapper (/opt/arkime/node_modules/async/dist/async.js:271:20)
    at replenish (/opt/arkime/node_modules/async/dist/async.js:441:29)
    at iterateeCallback (/opt/arkime/node_modules/async/dist/async.js:430:21)
    at /opt/arkime/node_modules/async/dist/async.js:327:20
    at invokeCallback (/opt/arkime/node_modules/async/dist/async.js:182:13)
    at /opt/arkime/node_modules/async/dist/async.js:174:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.19.1
```

**Comment by awick** [comment]
Can you try a newer version of arkime? How were the files added to arkime?

**Comment by cpockrandt** [comment]
> Can you try a newer version of arkime? How were the files added to arkime?

We just updated to 5.2.0 and will test it in the next weeks. If we encounter crashes again, we'll report ist.

**Comment by awick** [comment]
ok, but how were the files added to arkime? is it a pcap you can share?

**Comment by cpockrandt** [comment]
They were added via capture from s3 storage with s3http.

It might also be noteworthy, that the error didn't seem to be deterministic. Both crashes happened on expanding a session. But after restarting the viewer and expanding the same session again, it didn't crash again.

Unfortunately, we don't have the instance running anymore and cannot retrieve which of the files caused the issue.

**Comment by awick** [comment]
if you find more details please reopen.
